import { randomUUID } from "node:crypto";
import { Router } from "express";
import { env } from "../config/env";
import { collections, db, getDocOrNull, nowIso } from "../firestore/db";
import { asyncHandler, badRequest, notFound } from "../middleware/errorHandler";
import { validateBody } from "../middleware/validate";
import type { DemoSession } from "../types/domain";
import { selectDemoUserSchema } from "../validation/schemas";
export const demoRouter = Router();
demoRouter.post("/demo/session", asyncHandler(async (_req, res) => { const now = nowIso(); const session: DemoSession = { id: `demo_session_${randomUUID()}`, createdAt: now, updatedAt: now, seedVersion: env.demoSeedVersion }; await db.collection(collections.demoSessions).doc(session.id).set(session); res.status(201).json({ data: session }); }));
demoRouter.get("/demo/session", asyncHandler(async (req, res) => { const id = req.demoContext.demoSessionId; if (!id) throw badRequest("X-Demo-Session-Id header is required"); const session = await getDocOrNull<DemoSession>(collections.demoSessions, id); if (!session) throw notFound(`Demo session ${id} not found`); res.json({ data: session }); }));
demoRouter.post("/demo/select-user", validateBody(selectDemoUserSchema), asyncHandler(async (req, res) => { const id = req.demoContext.demoSessionId; if (!id) throw badRequest("X-Demo-Session-Id header is required"); if (req.body.userId && !(await db.collection(collections.users).doc(req.body.userId).get()).exists) throw notFound(`User ${req.body.userId} not found`); const ref = db.collection(collections.demoSessions).doc(id); if (!(await ref.get()).exists) throw notFound(`Demo session ${id} not found`); await ref.update({ selectedUserId: req.body.userId ?? null, updatedAt: nowIso() }); res.json({ data: await getDocOrNull<DemoSession>(collections.demoSessions, id) }); }));
